image: Fix include for use of ptrdiff
Commit 38fbe621 added use of the ptrdiff_t type in a header file,
however `make distcheck` complains:

In file included from headers-standalone-tmp.c:1:0:
../../../src/cairo-image-surface-private.h:74:5: error: unknown type name ‘ptrdiff_t’
     ptrdiff_t stride;
     ^